# build.yml

# Workflow's name
name: Build MediaGo App

# Workflow's trigger
on:
  push:
    branches:
      - master
  workflow_dispatch:

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-13, ubuntu-latest]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v5

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"

      # step4: install python env
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      # step5: install pnpm env
      - uses: pnpm/action-setup@v3
        with:
          version: "10.15.0"
          run_install: true

      - name: Build  & release app
        run: pnpm release:electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APP_TD_APPID: ${{ secrets.APP_TD_APPID }}

      - uses: actions/upload-artifact@v4
        with:
          name: mediago-${{ matrix.os }}
          path: apps/electron/release/mediago-*
